/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Locadora01;

/**
 *
 * @author F146DSq
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mbPrincipal = new javax.swing.JMenuBar();
        mbArquivo = new javax.swing.JMenu();
        smbSair = new javax.swing.JMenuItem();
        mbCadastro = new javax.swing.JMenu();
        smbFornecedor = new javax.swing.JMenuItem();
        smbCliente = new javax.swing.JMenuItem();
        smbMidia = new javax.swing.JMenuItem();
        Movimentacao = new javax.swing.JMenu();
        mbEmprestimo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mbPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mbArquivo.setText("Arquivo");

        smbSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.CTRL_MASK));
        smbSair.setText("Sair");
        mbArquivo.add(smbSair);

        mbPrincipal.add(mbArquivo);

        mbCadastro.setText("Cadastro");

        smbFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        smbFornecedor.setText("Fornecedor");
        smbFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smbFornecedorActionPerformed(evt);
            }
        });
        mbCadastro.add(smbFornecedor);

        smbCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        smbCliente.setText("Cliente");
        smbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smbClienteActionPerformed(evt);
            }
        });
        mbCadastro.add(smbCliente);

        smbMidia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        smbMidia.setText("Midia");
        mbCadastro.add(smbMidia);

        mbPrincipal.add(mbCadastro);

        Movimentacao.setText("Movimento");

        mbEmprestimo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mbEmprestimo.setText("Emprestimo");
        mbEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbEmprestimoActionPerformed(evt);
            }
        });
        Movimentacao.add(mbEmprestimo);

        mbPrincipal.add(Movimentacao);

        setJMenuBar(mbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 893, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smbFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smbFornecedorActionPerformed
        frmTabelaFornecedores dialog = new frmTabelaFornecedores();
        dialog.setVisible(true);
        setLocationRelativeTo(null);
    }//GEN-LAST:event_smbFornecedorActionPerformed

    private void smbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smbClienteActionPerformed
        frmTabelaClientes dialog = new frmTabelaClientes();
        dialog.setVisible(true);
        setLocationRelativeTo(null);
    }//GEN-LAST:event_smbClienteActionPerformed

    private void mbEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbEmprestimoActionPerformed
        frmMovimentacao dialog = new frmMovimentacao();
        dialog.setVisible(true);
        setLocationRelativeTo(null);
    }//GEN-LAST:event_mbEmprestimoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Movimentacao;
    private javax.swing.JMenu mbArquivo;
    private javax.swing.JMenu mbCadastro;
    private javax.swing.JMenuItem mbEmprestimo;
    private javax.swing.JMenuBar mbPrincipal;
    private javax.swing.JMenuItem smbCliente;
    private javax.swing.JMenuItem smbFornecedor;
    private javax.swing.JMenuItem smbMidia;
    private javax.swing.JMenuItem smbSair;
    // End of variables declaration//GEN-END:variables
}
